apiVersion: v1
kind: Service
metadata:
  name: demo-nodejs-service
  namespace: argocd
  labels:
    app: demo-nodejs
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: demo-nodejs