apiVersion: v1
kind: Service
metadata:
  name: demo-nodejs-service
  namespace: argocd
  labels:
    app: demo-nodejs
spec:
  ports:
    - name: demo-nodejs
      targetPort: 8081
      port: 8081
      nodePort: 30253
      protocol: TCP
  selector:
    app: demo-nodejs
  type: NodePort
