apiVersion: v1
kind: Service
metadata:
  name: demo-nodejs-service
  namespace: argocd
  labels:
    app: demo-nodejs
spec:
  ports:
    - port: 8080
      nodePort: 8080
  selector:
    app: demo-nodejs
  type: NodePort
